export const queries = {
    get_restaurantes: "SELECT id_restaurante,local,nombre,direccion,telefono FROM restaurante;",
    get_restaurante: "SELECT id_restaurante,local,nombre,direccion,telefono FROM restaurante WHERE id_restaurante = ?;",
    post_restaurante: "INSERT INTO restaurante (id_restaurante, local, nombre, direccion, telefono) VALUES (?,?,?,?,?)",
    update_restaurante: "UPDATE restaurante SET local = ?,nombre = ?,direccion = ?,telefono = ? WHERE  id_restaurante = ?",
    delete_restaurante: "DELETE FROM restaurante WHERE id_restaurante = ?",

    get_telefonos: "SELECT id_telfonico, num_telefono_movil, num_telefono_fijo FROM telefono",
    get_telefono: "SELECT id_telefonico, num_telefono_movil, num_telefono_fijo FROM telefono WHERE id_telefonico = ?",
    post_telefono: "INSERT INTO telefono (id_telefonico, num_telefono_movil, num_telefono_fijo) VALUES (?,?,?)",
    update_telefono: "UPDATE telefono SET num_telefono_movil = ?, num_telefono_fijo = ? WHERE id_telefonico = ?",
    delete_telefono: "DELETE FROM telefono WHERE id_telefonico = ?",

    get_direcciones: "SELECT id_direcciones, provincia, canton, distrito, direccion FROM direcciones",
    get_direccion: "SELECT id_direcciones, provincia, canton, distrito, direccion FROM direcciones WHERE id_direcciones = ?",
    post_direccion: "INSERT INTO direcciones (id_direcciones, provincia, canton, distrito, direccion) VALUES (?,?,?,?,?)",
    update_direccion: "UPDATE direcciones SET provincia = ?, canton = ?, distrito = ?, direccion = ? WHERE id_direcciones = ?",
    delete_direccion: "DELETE FROM direcciones WHERE id_direcciones",

    get_mesas: "SELECT id_mesas, nombre, estado, restaurante FROM mesa",
    get_mesa: "SELECT id_mesas, nombre, estado, restaurante FROM mesa WHERE id_mesas = ?",
    post_mesa: "INSERT INTO mesa (nombre, estado, restaurante) VALUES(?,?,?)",
    update_mesa: "UPDATE mesa SET nombre = ?, estado = ?, restaurante = ? WHERE id_mesas = ?",
    delete_mesa: "DELETE FROM mesa WHERE id_mesas",

    get_menus: "SELECT id_menu, nombre, restaurante FROM menu",
    get_menu: "SELECT id_menu, nombre, restaurante FROM menu WHERE id_menu = ?",
    post_menu: "INSERT INTO menu (nombre, restaurante) VALUES(?,?)",
    update_menu: "UPDATE menu SET nombre = ?, restaurante = ? WHERE id_menu = ?",
    delete_menu: "DELETE FROM menu WHERE id_menu",

    get_inventarios: "SELECT id_inventario, restaurante, articulo, cantidad, fecha_caducidad FROM inventario",
    get_inventario: "SELECT id_inventario, restaurante, articulo, cantidad, fecha_caducidad FROM inventario WHERE id_inventario = ?",
    post_inventario: "INSERT INTO inventario (restaurante, articulo, cantidad, fecha_caducidad) VALUES(?,?,?,?)",
    update_inventario: "UPDATE inventario SET restaurante = ?, articulo = ?, cantidad = ?, fecha_caducidad = ? WHERE id_inventario = ?",
    delete_inventario: "DELETE FROM inventario WHERE id_inventario",

    get_ingredintes_platillos: "SELECT id_ingredintes_platillo, ingrediente, platillo FROM ingredientes_platillo",
    get_ingredinte_platillo: "SELECT id_ingredintes_platillo, ingrediente, platillo FROM ingredientes_platillo WHERE id_ingredientes_platillo = ?",
    post_ingrediente_platillo: "INSERT INTO ingredientes_platillo (ingredientes, platillo) VALUES(?,?)",
    update_ingredinte_platillo: "UPDATE ingredientes_platillo SET ingredintes = ?, platillo = ?  WHERE id_ingredientes_platillo = ?",
    delete_ingredinte_platillo: "DELETE FROM ingredientes_platillo WHERE id_ingredientes_platillo",

    get_clientes: "SELECT id_clientes,cedula,nombre,direccio,telefono FROM cliente",
    get_cliente: "SELECT id_clientes,cedula,nombre,direccio,telefono FROM cliente WHERE id_clientes = ?",
    post_cliente: "INSERT INTO cliente (cedula,nombre,direccio,telefono) VALUES(?,?,?,?)",
    update_cliente: "UPDATE cliente SET cedula = ?, nombre = ?, direccion = ?, telefono = ? WHERE id_clientes = ?",
    delete_cliente: "DELETE FROM cliente WHERE id_clientes",

    get_reservaciones: "SELECT id_reservacion, restaurante, cliente, mesa, duracion, fecha   FROM reservacion",
    get_reservacion: "SELECT id_reservacion, restaurante, cliente, mesa, duracion, fecha   FROM reservacion WHERE id_reservacion = ?",
    post_reservacion: "INSERT INTO reservacion (restaurante, cliente, mesa, duracion, fecha) VALUES(?,?,?,?,?)",
    update_reservacion: "UPDATE reservacion SET restaurante = ?, cliente = ?, mesa = ?, duracion = ?, fecha = ? WHERE id_reservacion = ?",
    delete_reservacion: "DELETE FROM reservacion WHERE id_reservacion",

    get_platillos: "SELECT id_platillo, nombre FROM platillo",
    get_platillo: "SELECT id_platillo, nombre FROM platillo WHERE id_platillo = ?",
    post_platillo: "INSERT INTO platillo (nombre) VALUES(?)",
    update_platillo: "UPDATE platillo SET nombre = ? WHERE id_platillo = ?",
    delete_platillo: "DELETE FROM platillo WHERE id_platillo",

    get_pedido_articulos: "SELECT id_pedido_articulo, pedido, articulo, tipo FROM pedido_articulo",
    get_pedido_articulo: "SELECT id_pedido_articulo, pedido, articulo, tipo FROM pedido_articulo WHERE id_pedido_articulo = ?",
    post_pedido_articulo: "INSERT INTO pedido_articulo (pedido, articulo, tipo) VALUES(?,?,?)",
    update_pedido_articulo: "UPDATE pedido_articulo SET pedido = ?, articulo = ?, tipo = ? WHERE id_pedido_articulo = ?",
    delete_pedido_articulo: "DELETE FROM pedido_articulo WHERE id_pedido_articulo",

    get_pedidos: "SELECT id_pedido, menu FROM pedido",
    get_pedido: "SELECT id_pedido, menu FROM pedido WHERE id_pedido = ?",
    post_pedido: "INSERT INTO pedido (menu) VALUES(?)",
    update_pedido: "UPDATE pedido SET menu = ? WHERE id_pedido = ?",
    delete_pedido: "DELETE FROM pedido WHERE id_pedido",

    get_ordenes: "SELECT id_orden, cliente, pedido fecha FROM orden",
    get_orden: "SELECT id_orden, cliente, pedido fecha FROM orden WHERE id_orden = ?",
    post_orden: "INSERT INTO orden (cliente, pedido) VALUES(?,?)",
    update_orden: "UPDATE orden SET cliente = ?, pedido = ? WHERE id_orden = ?",
    delete_orden: "DELETE FROM orden WHERE id_orden",

    get_ingredintes: "SELECT id_ingrediente, articulo FROM ingredientes",
    get_ingredinte: "SELECT id_ingrediente, articulo FROM ingredientes WHERE id_ingrediente = ?",
    post_ingrediente: "INSERT INTO ingredientes (articulo) VALUES(?)",
    update_ingrediente: "UPDATE ingredientes SET articulo = ? WHERE id_ingrediente = ?",
    delete_ingrediente: "DELETE FROM ingredientes WHERE id_ingrediente",

    get_bebida: "SELECT id_bebida, articulo FROM bebida",
    get_bebidas: "SELECT id_bebida, articulo FROM bebida WHERE id_bebida = ?",
    post_bebida: "INSERT INTO bebida (articulo) VALUES(?)",
    update_bebida: "UPDATE bebida SET articulo = ? WHERE id_bebida = ?",
    delete_bebida: "DELETE FROM bebida WHERE id_bebida",

    get_articulo_menu: "SELECT id_articulo_menu, menu, bebidas, platillo FROM articulo_menu",
    get_articulo_menus: "SELECT id_articulo_menu, menu, bebidas, platillo FROM articulo_menu WHERE id_articulo_menu = ?",
    post_articulo_menu: "INSERT INTO articulo_menu (menu, bebidas, platillo) VALUES(?,?,?)",
    update_articulo_menu: "UPDATE articulo_menu SET menu = ?, bebidas = ?, platillo = ? WHERE id_articulo_menu = ?",
    delete_articulo_menu: "DELETE FROM articulo_menu WHERE id_articulo_menu",
}
