export const queries = {
    get_restaurantes: "SELECT id_restaurante,local,nombre,direccion,telefono FROM restaurante;",
    get_restaurante: "SELECT id_restaurante,local,nombre,direccion,telefono FROM restaurante WHERE id_restaurante = ?;",
    post_restaurante: "INSERT INTO restaurante (local, nombre, direccion, telefono) VALUES (?,?,?,?)",
    update_restaurante: "UPDATE restaurante SET local = ?, nombre = ?, direccion = ?, telefono = ? WHERE  id_restaurante = ?",
    delete_restaurante: "DELETE FROM restaurante WHERE id_restaurante = ?",

    get_telefonos: "SELECT id_telfonico, num_telefono_movil, num_telefono_fijo FROM telefono",
    get_telefono: "SELECT id_telefonico, num_telefono_movil, num_telefono_fijo FROM telefono WHERE id_telefonico = ?",
    post_telefono: "INSERT INTO telefono (num_telefono_movil, num_telefono_fijo) VALUES (?,?)",
    update_telefono: "UPDATE telefono SET num_telefono_movil = ?, num_telefono_fijo = ? WHERE id_telefonico = ?",
    delete_telefono: "DELETE FROM telefono WHERE id_telefonico = ?",

    get_direcciones: "SELECT id_direcciones, provincia, canton, distrito, direccion FROM direcciones",
    get_direccion: "SELECT id_direcciones, provincia, canton, distrito, direccion FROM direcciones WHERE id_direcciones = ?",
    post_direccion: "INSERT INTO direcciones (provincia, canton, distrito, direccion) VALUES (?,?,?,?)",
    update_direccion: "UPDATE direcciones SET provincia = ?, canton = ?, distrito = ?, direccion = ? WHERE id_direcciones = ?",
    delete_direccion: "DELETE FROM direcciones WHERE id_direcciones = ?",

    get_articulo: "SELECT id_articulo, restaurante, articulo, cantidad, fecha_caducidad, tipo FROM inventario WHERE restaurante = ? AND id_articulo = ?",
    get_inventario: "SELECT id_articulo, restaurante, articulo, cantidad, fecha_caducidad, tipo FROM inventario WHERE restaurante = ?",
    get_ingrediente: "SELECT id_articulo, restaurante, articulo, cantidad, fecha_caducidad, tipo FROM inventario WHERE id_articulo = ?",
    get_inventario_tipo: "SELECT id_articulo, restaurante, articulo, cantidad, fecha_caducidad, tipo FROM inventario WHERE restaurante = ? AND tipo = ?",
    post_articulo: "INSERT INTO inventario (restaurante, articulo, cantidad, fecha_caducidad, tipo) VALUES(?,?,?,?,?)",
    update_articulo: "UPDATE inventario SET articulo = ?, cantidad = ?, fecha_caducidad = ?, tipo = ? WHERE restaurante = ? AND id_articulo = ?",
    delete_articulo: "DELETE FROM inventario WHERE id_articulo = ?",

    get_platillo: "SELECT id_platillos, nombre FROM platillos WHERE id_platillos = ?",
    get_platillos: "SELECT id_platillos, nombre FROM platillos",
    get_platillo: "SELECT id_platillos, nombre FROM platillos WHERE id_platillos IN (?)",
    post_platillo: "INSERT INTO platillos (nombre) VALUES (?)",
    update_platillo: "UPDATE platillos SET nombre = ? WHERE id_platillos = ?",
    delete_platillo: "DELETE FROM platillos WHERE id_platillos = ?",

    get_platillo_ingredintes: "SELECT id_platillo_ingrediente, platillo, ingrediente FROM platillo_ingredientes WHERE platillo = ?",
    post_platillo_ingredientes: "INSERT INTO platillo_ingredientes (platillo, ingrediente) VALUES(?,?)",
    update_platillo_ingredientes: "UPDATE platillo_ingredientes SET platillo = ?, ingredinte = ? WHERE id_platillo_ingrediente = ?",
    delete_platillo_ingredientes: "DELETE FROM platillo_ingredientes WHERE platillo = ?",

    get_menu: "SELECT id_menu, restaurante, nombre FROM menu WHERE id_menu = ?",
    get_menus: "SELECT id_menu, restaurante, nombre FROM menu",
    get_menu_restaurante: "SELECT id_menu, restaurante, nombre FROM menu WHERE restaurante = ?",
    post_menu: "INSERT INTO menu (restaurante, nombre) VALUES(?,?)",
    update_menu: "UPDATE menu SET nombre = ? WHERE id_menu = ?",
    delete_menu: "DELETE FROM menu WHERE id_menu = ?",
    
    get_menu_articulo: "SELECT id_menu_articulos, menu, articulo, tipo FROM menu_articulos WHERE menu = ?",
    get_menu_articulo_tipo: "SELECT id_menu_articulos, menu, articulo, tipo FROM menu_articulos WHERE menu = ? AND tipo = ?",
    post_menu_articulo: "INSERT INTO menu_articulos (menu, articulo, tipo) VALUES(?,?,?)",
    update_menu_articulo: "UPDATE menu_articulos SET articulo = ?, tipo = ? WHERE id_menu_articulos = ?",
    delete_menu_articulo: "DELETE FROM menu_articulos WHERE id_menu_articulos = ?",

    get_cliente: "SELECT id_clientes, restaurante, cedula, nombre, direccion, telefono FROM clientes WHERE id_clientes = ?",
    get_cliente_by_cedula: "SELECT id_clientes, restaurante, cedula, nombre, direccion, telefono FROM clientes WHERE cedula = ?",
    get_cliente_by_restaurante: "SELECT id_clientes, restaurante, cedula, nombre, direccion, telefono FROM clientes WHERE restaurante = ?",
    post_cliente: "INSERT INTO clientes (restaurante, cedula, nombre, direccion, telefono) VALUES(?,?,?,?,?)",
    update_cliente: "UPDATE clientes SET restaurante = ?, cedula = ?, nombre = ?, direccion = ?, telefono = ? WHERE id_clientes = ?",
    delete_cliente: "DELETE FROM clientes WHERE id_clientes = ?",

    get_mesa: "SELECT id_mesas, nombre, estado, restaurante FROM mesas WHERE id_mesas = ?",
    get_mesas: "SELECT id_mesas, nombre, estado, restaurante FROM mesas WHERE restaurante = ?",
    post_mesa: "INSERT INTO mesas (nombre, estado, restaurante) VALUES(?,?,?)",
    update_mesa: "UPDATE mesas SET nombre = ?, estado = ? WHERE id_mesas = ? AND restaurante = ?",
    update_mesa_estado: "UPDATE mesas SET estado = ? WHERE id_mesas = ? AND restaurante = ?",
    delete_mesa: "DELETE FROM mesas WHERE id_mesas = ?",

    get_reservacion: "SELECT id_reservaciones, restaurante, cliente, mesa, duracion, fecha   FROM reservaciones WHERE id_reservaciones = ?",
    get_reservaciones: "SELECT id_reservaciones, restaurante, cliente, mesa, duracion, fecha FROM reservaciones WHERE restaurante = ?",
    post_reservacion: "INSERT INTO reservaciones (restaurante, cliente, mesa, duracion, fecha) VALUES(?,?,?,?,?)",
    update_reservacion: "UPDATE reservaciones SET restaurante = ?, cliente = ?, mesa = ?, duracion = ?, fecha = ? WHERE id_reservaciones = ?",
    delete_reservacion: "DELETE FROM reservaciones WHERE id_reservaciones = ?",
    
    get_orden: "SELECT id_orden, restaurante, mesa, cliente, fecha, estado FROM ordenes WHERE id_orden = ?",
    get_ordenes: "SELECT id_orden, restaurante, mesa, cliente, fecha, estado FROM ordenes WHERE restaurante = ?",
    post_orden: "INSERT INTO ordenes (restaurante, mesa, cliente, fecha, estado) VALUES(?,?,?,?,?)",
    update_orden: "UPDATE ordenes SET restaurante = ?, mesa = ?, cliente = ?, fecha = ?, estado = ? WHERE id_orden = ?",
    update_orden_estado: "UPDATE ordenes SET estado = ? WHERE id_orden = ?",
    delete_orden: "DELETE FROM ordenes WHERE id_orden = ?",

    get_orden_articulos: "SELECT orden, articulo, tipo FROM orden_articulos WHERE orden = ?",
    post_orden_articulos: "INSERT INTO orden_articulos (orden, articulo, tipo) VALUES(?,?,?)",
    update_orden_articulos: "UPDATE orden_articulos SET articulo = ?, tipo = ? WHERE orden = ? and articulo = ?",
    delete_orden_articulos: "DELETE FROM orden_articulos WHERE orden = ? AND articulo = ? AND tipo = ?",
    delete_orden_articulos_orden: "DELETE FROM orden_articulos WHERE orden = ?",

    get_usuario: "SELECT id_usuarios, restaurante, nombre_usuario, contraseña, correo, rol, bloqueada FROM usuarios WHERE id_usuarios = ?",
    get_usuarios: "SELECT id_usuarios, restaurante, nombre_usuario, contraseña, correo, rol, bloqueada FROM usuarios",
    get_usuario_login: "SELECT id_usuarios, restaurante, nombre_usuario, contraseña, correo, rol, bloqueada FROM usuarios WHERE nombre_usuario = ? AND contraseña = ?",
    get_usuarios_restaurante: "SELECT id_usuarios, restaurante, nombre_usuario, contraseña, correo, rol, bloqueada FROM usuarios WHERE restaurante = ?",
    post_usuario: "INSERT INTO usuarios (restaurante, nombre_usuario, contraseña, correo, rol, bloqueada) VALUES(?,?,?,?,?,?)",
    update_usuario: "UPDATE usuarios SET restaurante = ?, nombre_usuario = ?, contraseña = ?, correo = ?, rol = ?, bloqueada = ? WHERE id_usuarios = ?",
    delete_usuario: "DELETE FROM usuarios WHERE id_usuarios = ?",

    get_login: "SELECT id_usuario, fecha, estado FROM login WHERE id_usuario = ?",
    get_logins: "SELECT id_usuario, fecha, estado FROM login",
    post_login: "INSERT INTO login (id_usuario, fecha, estado) VALUES(?,?,?)",
    update_login: "UPDATE login SET fecha = ?, estado = ? WHERE id_usuario = ?",
    delete_login: "DELETE FROM login WHERE id_usuario = ?",
}
